- name: Pre-requisites Processes
  hosts: localhost
  gather_facts: no
  become: yes
  become_user: root

  vars:
   - terraform_binary:
       src: " https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip"
       dest: "{{ lookup('env','HOME') }}/.local/bin"
  
   - terraform_provider_libvirt:
       src: "https://github.com/dmacvicar/terraform-provider-libvirt/releases/download/v0.6.1/terraform-provider-libvirt-0.6.1+git.1578064534.db13b678.Fedora_28.x86_64.tar.gz"
       dest: "{{ lookup('env','HOME') }}/.terraform.d/plugins"

   - terraform_provider_matchbox:
       src: "https://github.com/poseidon/terraform-provider-matchbox/releases/download/v0.3.0/terraform-provider-matchbox-v0.3.0-linux-amd64.tar.gz"
       dest: "{{ lookup('env','HOME') }}/.terraform.d/plugins"

   - rhcos_kernel:
       src: "{{ rhcos_kernel_src }}"
       dest: "/var/lib/matchbox/{{ rhcos_kernel_path }}"

   - rhcos_initramfs:
       src: "{{ rhcos_initramfs_src }}"
       dest: "/var/lib/matchbox/{{ rhcos_initramfs_path }}"

   - rhcos_bios:
       src: "{{ rhcos_bios_src }}"
       dest: "{{ webserver_doc_path }}/rhcos-bios.raw.gz"

   - openshift_installer:
       src: "{{ openshift_installer_src }}"
       dest: "/usr/bin"

   - matchbox_git_repo:
       src: "https://github.com/poseidon/matchbox/archive/master.zip"
       dest: "{{ lookup('env','PWD') }}"

  pre_tasks:
    - debug: var=rhcos_initramfs
    - name: Create directories
      file: 
        path: "{{ item }}"
        state: directory
      with_items:
      - "{{ terraform_binary.dest | dirname }}"
      - "{{ terraform_provider_libvirt.dest | dirname }}"
      - "{{ rhcos_kernel.dest | dirname }}"
      - "{{ webserver_doc_path }}"

  tasks:
    - name: Download terraform binary & libvirt provider
      unarchive:
        src: "{{ item.src }}" 
        dest: "{{ item.dest }}"
        mode: '0777'
        remote_src: yes
      with_items:
      - "{{ terraform_binary }}"
      - "{{ terraform_provider_libvirt }}"
      - "{{ terraform_provider_matchbox }}"
      - "{{ openshift_installer }}"
      - "{{ matchbox_git_repo }}"

    - set_fact:
        matchbox_dir: "{{ (terraform_provider_matchbox.src | basename | splitext)[0] }}"

    - name: Check if matachbox provider exist    
      stat:
        path: "{{ terraform_provider_matchbox.dest }}/terraform-provider-matchbox"
      register: matchbox_provider_exist

    - name: Move matchbox provider
      copy:
        src: "{{ terraform_provider_matchbox.dest }}/{{ (matchbox_dir | splitext)[0] }}/terraform-provider-matchbox"
        dest: "{{ terraform_provider_matchbox.dest }}/terraform-provider-matchbox"

    - name: Remove matchbox folder
      file:
        path: "{{ terraform_provider_matchbox.dest }}/{{ (matchbox_dir | splitext)[0] }}"
        state: absent
 
    - name: Download RHCOS kernal and initramfs
      get_url:
        url: "{{ item.src }}"
        dest: "{{ item.dest | dirname }}/{{ item.dest | basename }}"
      with_items:
      - "{{ rhcos_kernel }}"
      - "{{ rhcos_initramfs }}"
      - "{{ rhcos_bios }}"

